### PR TITLE
Preparing for new release

### PR DESCRIPTION
**Pull request by samwilson**
Is it time for a new release?

Changes since last release: https://github.com/addwiki/mediawiki-api-base/compare/2.3.1...master

I've updated the changelog here.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
It is unusual to put CR changes into the release notes. The audience of release notes are the consumers of the package, and they normally do not care about internal changes that do not affect them.

**Comment by samwilson** [comment]
Good point; removed.

Is it ready to tag for 2.4.0 do you think?

**Comment by JeroenDeDauw** [comment]
I'm all for frequent releases. Not my project tho :)

**Review by JeroenDeDauw — APPROVED** [review]

**Comment by samwilson** [comment]
(bump)

**Comment by samwilson** [comment]
@addshore what do you think? (sorry to keep pestering!)

**Pull request merged**
