### PR TITLE
Adds csrf token to action=logout requests

### PR DESCRIPTION
**Pull request by Tpt**
Should fix https://phabricator.wikimedia.org/T223106

### CODE REVIEW

**Comment by addshore** [comment]
Seem to be a lot of failures :( 
But the commit itself looks good?

**Comment by Tpt** [comment]
The CI errors does not seem related to this change.
* hhvm fails because composer does not support hhvm anymore
* php 5.* fails because of MediaWiki configuration error (too old PHP version?)
* php 7.1 fails with `PHPUnit_Framework_ExceptionWrapper::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/travis/build/addwiki/mediawiki-api-base/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0`

**Comment by samwilson** [comment]
Can we drop hhvm now? And I think the issues with PHP7.1's built-in server are resolved. And can we drop testing on end-of-life MediaWiki versions (we still need to support MW1.27 for another month or so)? I'm having a crack at fixing these in #45.

**Comment by addshore** [comment]
> Can we drop hhvm now?

I think so

> And I think the issues with PHP7.1's built-in server are resolved. And can we drop testing on end-of-life MediaWiki versions (we still need to support MW1.27 for another month or so)? I'm having a crack at fixing these in #45.

Also sounds good!

**Comment by addshore** [comment]
I'm going to merge this as it looks fine, need to fix CI at some other time..

**Pull request merged**
