### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by samwilson**
* Use more recent PhpUnit.
* Update CI to supported MediaWiki version.

### CODE REVIEW

**Comment by samwilson** [comment]
All I was trying to do was locate the cause of this error that I was getting, but it seems now it's getting different ones :(

> 1) Mediawiki\Api\Test\Integration\MediawikiApiTest::testNewFromPageInvalidHtml
Failed asserting that exception of type "GuzzleHttp\Exception\RequestException" matches expected exception "Mediawiki\Api\RsdException". Message was: "cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**Comment by addshore** [comment]
So much red CI :/

**Comment by samwilson** [comment]
Yep! :-( I thought it was going to be an easy fix, but now I'm discouraged and there's other things to work on.

**Comment by addshore** [comment]
This has all been done in the mono repo over the past weeks!
Take a look!

**Pull request closed without merging**
