### PR TITLE
README.md s/fill/full/

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Review by samwilson — APPROVED** [review]

**Comment by reedy** [comment]
URL is a 404 though

**Comment by samwilson** [comment]
I guess it should be https://addwiki.github.io/v3/mediawiki-api-base/ instead. I guess it's possible to add a redirect (although from memory Github Pages doesn't support HTTP redirects, only HTML ones… or maybe there's some Jekyll trick).

Actually I feel a bit out of touch with things here since the switch to the monorepo… @addshore should this have been updated at https://github.com/addwiki/addwiki/blob/main/packages/mediawiki-api-base/README.md instead, or is there some magic going on?

**Comment by addshore** [comment]
This needs to be in the mono repo now at https://github.com/addwiki/addwiki

So the latest merge there overwrote the change.
I'll go and sync it now!

**Comment by addshore** [comment]
https://github.com/addwiki/addwiki/commit/1f86a582f2e54fb65531049cd1a1116a3327c51e

**Pull request merged**
